// MongoDB Atlas CDK Construct Library for AWS CloudFormation Resources
package mongodbatlas


// Human-readable label that identifies the metric against which MongoDB Cloud checks the alert.
type AlertViewMetricName string

const (
	// ASSERT_MSG.
	AlertViewMetricName_ASSERT_MSG AlertViewMetricName = "ASSERT_MSG"
	// ASSERT_REGULAR.
	AlertViewMetricName_ASSERT_REGULAR AlertViewMetricName = "ASSERT_REGULAR"
	// ASSERT_USER.
	AlertViewMetricName_ASSERT_USER AlertViewMetricName = "ASSERT_USER"
	// ASSERT_WARNING.
	AlertViewMetricName_ASSERT_WARNING AlertViewMetricName = "ASSERT_WARNING"
	// AVG_COMMAND_EXECUTION_TIME.
	AlertViewMetricName_AVG_COMMAND_EXECUTION_TIME AlertViewMetricName = "AVG_COMMAND_EXECUTION_TIME"
	// AVG_READ_EXECUTION_TIME.
	AlertViewMetricName_AVG_READ_EXECUTION_TIME AlertViewMetricName = "AVG_READ_EXECUTION_TIME"
	// AVG_WRITE_EXECUTION_TIME.
	AlertViewMetricName_AVG_WRITE_EXECUTION_TIME AlertViewMetricName = "AVG_WRITE_EXECUTION_TIME"
	// CACHE_BYTES_READ_INTO.
	AlertViewMetricName_CACHE_BYTES_READ_INTO AlertViewMetricName = "CACHE_BYTES_READ_INTO"
	// CACHE_BYTES_WRITTEN_FROM.
	AlertViewMetricName_CACHE_BYTES_WRITTEN_FROM AlertViewMetricName = "CACHE_BYTES_WRITTEN_FROM"
	// CACHE_DIRTY_BYTES.
	AlertViewMetricName_CACHE_DIRTY_BYTES AlertViewMetricName = "CACHE_DIRTY_BYTES"
	// CACHE_USED_BYTES.
	AlertViewMetricName_CACHE_USED_BYTES AlertViewMetricName = "CACHE_USED_BYTES"
	// COMPUTED_MEMORY.
	AlertViewMetricName_COMPUTED_MEMORY AlertViewMetricName = "COMPUTED_MEMORY"
	// CONNECTIONS.
	AlertViewMetricName_CONNECTIONS AlertViewMetricName = "CONNECTIONS"
	// CONNECTIONS_PERCENT.
	AlertViewMetricName_CONNECTIONS_PERCENT AlertViewMetricName = "CONNECTIONS_PERCENT"
	// CURSORS_TOTAL_OPEN.
	AlertViewMetricName_CURSORS_TOTAL_OPEN AlertViewMetricName = "CURSORS_TOTAL_OPEN"
	// CURSORS_TOTAL_TIMED_OUT.
	AlertViewMetricName_CURSORS_TOTAL_TIMED_OUT AlertViewMetricName = "CURSORS_TOTAL_TIMED_OUT"
	// DB_DATA_SIZE_TOTAL.
	AlertViewMetricName_DB_DATA_SIZE_TOTAL AlertViewMetricName = "DB_DATA_SIZE_TOTAL"
	// DB_INDEX_SIZE_TOTAL.
	AlertViewMetricName_DB_INDEX_SIZE_TOTAL AlertViewMetricName = "DB_INDEX_SIZE_TOTAL"
	// DB_STORAGE_TOTAL.
	AlertViewMetricName_DB_STORAGE_TOTAL AlertViewMetricName = "DB_STORAGE_TOTAL"
	// DISK_PARTITION_SPACE_USED_DATA.
	AlertViewMetricName_DISK_PARTITION_SPACE_USED_DATA AlertViewMetricName = "DISK_PARTITION_SPACE_USED_DATA"
	// DISK_PARTITION_SPACE_USED_INDEX.
	AlertViewMetricName_DISK_PARTITION_SPACE_USED_INDEX AlertViewMetricName = "DISK_PARTITION_SPACE_USED_INDEX"
	// DISK_PARTITION_SPACE_USED_JOURNAL.
	AlertViewMetricName_DISK_PARTITION_SPACE_USED_JOURNAL AlertViewMetricName = "DISK_PARTITION_SPACE_USED_JOURNAL"
	// DISK_PARTITION_UTILIZATION_DATA.
	AlertViewMetricName_DISK_PARTITION_UTILIZATION_DATA AlertViewMetricName = "DISK_PARTITION_UTILIZATION_DATA"
	// DISK_PARTITION_UTILIZATION_INDEX.
	AlertViewMetricName_DISK_PARTITION_UTILIZATION_INDEX AlertViewMetricName = "DISK_PARTITION_UTILIZATION_INDEX"
	// DISK_PARTITION_UTILIZATION_JOURNAL.
	AlertViewMetricName_DISK_PARTITION_UTILIZATION_JOURNAL AlertViewMetricName = "DISK_PARTITION_UTILIZATION_JOURNAL"
	// DOCUMENT_DELETED.
	AlertViewMetricName_DOCUMENT_DELETED AlertViewMetricName = "DOCUMENT_DELETED"
	// DOCUMENT_INSERTED.
	AlertViewMetricName_DOCUMENT_INSERTED AlertViewMetricName = "DOCUMENT_INSERTED"
	// DOCUMENT_RETURNED.
	AlertViewMetricName_DOCUMENT_RETURNED AlertViewMetricName = "DOCUMENT_RETURNED"
	// DOCUMENT_UPDATED.
	AlertViewMetricName_DOCUMENT_UPDATED AlertViewMetricName = "DOCUMENT_UPDATED"
	// EXTRA_INFO_PAGE_FAULTS.
	AlertViewMetricName_EXTRA_INFO_PAGE_FAULTS AlertViewMetricName = "EXTRA_INFO_PAGE_FAULTS"
	// FTS_MEMORY_RESIDENT.
	AlertViewMetricName_FTS_MEMORY_RESIDENT AlertViewMetricName = "FTS_MEMORY_RESIDENT"
	// FTS_MEMORY_SHARED.
	AlertViewMetricName_FTS_MEMORY_SHARED AlertViewMetricName = "FTS_MEMORY_SHARED"
	// FTS_MEMORY_VIRTUAL.
	AlertViewMetricName_FTS_MEMORY_VIRTUAL AlertViewMetricName = "FTS_MEMORY_VIRTUAL"
	// FTS_PROCESS_CPU_KERNEL.
	AlertViewMetricName_FTS_PROCESS_CPU_KERNEL AlertViewMetricName = "FTS_PROCESS_CPU_KERNEL"
	// FTS_PROCESS_CPU_USER.
	AlertViewMetricName_FTS_PROCESS_CPU_USER AlertViewMetricName = "FTS_PROCESS_CPU_USER"
	// FTS_PROCESS_DISK.
	AlertViewMetricName_FTS_PROCESS_DISK AlertViewMetricName = "FTS_PROCESS_DISK"
	// GLOBAL_LOCK_CURRENT_QUEUE_READERS.
	AlertViewMetricName_GLOBAL_LOCK_CURRENT_QUEUE_READERS AlertViewMetricName = "GLOBAL_LOCK_CURRENT_QUEUE_READERS"
	// GLOBAL_LOCK_CURRENT_QUEUE_TOTAL.
	AlertViewMetricName_GLOBAL_LOCK_CURRENT_QUEUE_TOTAL AlertViewMetricName = "GLOBAL_LOCK_CURRENT_QUEUE_TOTAL"
	// GLOBAL_LOCK_CURRENT_QUEUE_WRITERS.
	AlertViewMetricName_GLOBAL_LOCK_CURRENT_QUEUE_WRITERS AlertViewMetricName = "GLOBAL_LOCK_CURRENT_QUEUE_WRITERS"
	// LOGICAL_SIZE.
	AlertViewMetricName_LOGICAL_SIZE AlertViewMetricName = "LOGICAL_SIZE"
	// MEMORY_RESIDENT.
	AlertViewMetricName_MEMORY_RESIDENT AlertViewMetricName = "MEMORY_RESIDENT"
	// MEMORY_VIRTUAL.
	AlertViewMetricName_MEMORY_VIRTUAL AlertViewMetricName = "MEMORY_VIRTUAL"
	// NETWORK_BYTES_IN.
	AlertViewMetricName_NETWORK_BYTES_IN AlertViewMetricName = "NETWORK_BYTES_IN"
	// NETWORK_BYTES_OUT.
	AlertViewMetricName_NETWORK_BYTES_OUT AlertViewMetricName = "NETWORK_BYTES_OUT"
	// NETWORK_NUM_REQUESTS.
	AlertViewMetricName_NETWORK_NUM_REQUESTS AlertViewMetricName = "NETWORK_NUM_REQUESTS"
	// NORMALIZED_FTS_PROCESS_CPU_KERNEL.
	AlertViewMetricName_NORMALIZED_FTS_PROCESS_CPU_KERNEL AlertViewMetricName = "NORMALIZED_FTS_PROCESS_CPU_KERNEL"
	// NORMALIZED_FTS_PROCESS_CPU_USER.
	AlertViewMetricName_NORMALIZED_FTS_PROCESS_CPU_USER AlertViewMetricName = "NORMALIZED_FTS_PROCESS_CPU_USER"
	// NORMALIZED_SYSTEM_CPU_STEAL.
	AlertViewMetricName_NORMALIZED_SYSTEM_CPU_STEAL AlertViewMetricName = "NORMALIZED_SYSTEM_CPU_STEAL"
	// NORMALIZED_SYSTEM_CPU_USER.
	AlertViewMetricName_NORMALIZED_SYSTEM_CPU_USER AlertViewMetricName = "NORMALIZED_SYSTEM_CPU_USER"
	// OPCOUNTER_CMD.
	AlertViewMetricName_OPCOUNTER_CMD AlertViewMetricName = "OPCOUNTER_CMD"
	// OPCOUNTER_DELETE.
	AlertViewMetricName_OPCOUNTER_DELETE AlertViewMetricName = "OPCOUNTER_DELETE"
	// OPCOUNTER_GETMORE.
	AlertViewMetricName_OPCOUNTER_GETMORE AlertViewMetricName = "OPCOUNTER_GETMORE"
	// OPCOUNTER_INSERT.
	AlertViewMetricName_OPCOUNTER_INSERT AlertViewMetricName = "OPCOUNTER_INSERT"
	// OPCOUNTER_QUERY.
	AlertViewMetricName_OPCOUNTER_QUERY AlertViewMetricName = "OPCOUNTER_QUERY"
	// OPCOUNTER_REPL_CMD.
	AlertViewMetricName_OPCOUNTER_REPL_CMD AlertViewMetricName = "OPCOUNTER_REPL_CMD"
	// OPCOUNTER_REPL_DELETE.
	AlertViewMetricName_OPCOUNTER_REPL_DELETE AlertViewMetricName = "OPCOUNTER_REPL_DELETE"
	// OPCOUNTER_REPL_INSERT.
	AlertViewMetricName_OPCOUNTER_REPL_INSERT AlertViewMetricName = "OPCOUNTER_REPL_INSERT"
	// OPCOUNTER_REPL_UPDATE.
	AlertViewMetricName_OPCOUNTER_REPL_UPDATE AlertViewMetricName = "OPCOUNTER_REPL_UPDATE"
	// OPCOUNTER_UPDATE.
	AlertViewMetricName_OPCOUNTER_UPDATE AlertViewMetricName = "OPCOUNTER_UPDATE"
	// OPERATIONS_SCAN_AND_ORDER.
	AlertViewMetricName_OPERATIONS_SCAN_AND_ORDER AlertViewMetricName = "OPERATIONS_SCAN_AND_ORDER"
	// OPLOG_MASTER_LAG_TIME_DIFF.
	AlertViewMetricName_OPLOG_MASTER_LAG_TIME_DIFF AlertViewMetricName = "OPLOG_MASTER_LAG_TIME_DIFF"
	// OPLOG_MASTER_TIME.
	AlertViewMetricName_OPLOG_MASTER_TIME AlertViewMetricName = "OPLOG_MASTER_TIME"
	// OPLOG_RATE_GB_PER_HOUR.
	AlertViewMetricName_OPLOG_RATE_GB_PER_HOUR AlertViewMetricName = "OPLOG_RATE_GB_PER_HOUR"
	// OPLOG_SLAVE_LAG_MASTER_TIME.
	AlertViewMetricName_OPLOG_SLAVE_LAG_MASTER_TIME AlertViewMetricName = "OPLOG_SLAVE_LAG_MASTER_TIME"
	// QUERY_EXECUTOR_SCANNED.
	AlertViewMetricName_QUERY_EXECUTOR_SCANNED AlertViewMetricName = "QUERY_EXECUTOR_SCANNED"
	// QUERY_EXECUTOR_SCANNED_OBJECTS.
	AlertViewMetricName_QUERY_EXECUTOR_SCANNED_OBJECTS AlertViewMetricName = "QUERY_EXECUTOR_SCANNED_OBJECTS"
	// QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED.
	AlertViewMetricName_QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED AlertViewMetricName = "QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED"
	// QUERY_TARGETING_SCANNED_PER_RETURNED.
	AlertViewMetricName_QUERY_TARGETING_SCANNED_PER_RETURNED AlertViewMetricName = "QUERY_TARGETING_SCANNED_PER_RETURNED"
	// RESTARTS_IN_LAST_HOUR.
	AlertViewMetricName_RESTARTS_IN_LAST_HOUR AlertViewMetricName = "RESTARTS_IN_LAST_HOUR"
	// SERVERLESS_CONNECTIONS.
	AlertViewMetricName_SERVERLESS_CONNECTIONS AlertViewMetricName = "SERVERLESS_CONNECTIONS"
	// SERVERLESS_CONNECTIONS_PERCENT.
	AlertViewMetricName_SERVERLESS_CONNECTIONS_PERCENT AlertViewMetricName = "SERVERLESS_CONNECTIONS_PERCENT"
	// SERVERLESS_DATA_SIZE_TOTAL.
	AlertViewMetricName_SERVERLESS_DATA_SIZE_TOTAL AlertViewMetricName = "SERVERLESS_DATA_SIZE_TOTAL"
	// SERVERLESS_NETWORK_BYTES_IN.
	AlertViewMetricName_SERVERLESS_NETWORK_BYTES_IN AlertViewMetricName = "SERVERLESS_NETWORK_BYTES_IN"
	// SERVERLESS_NETWORK_BYTES_OUT.
	AlertViewMetricName_SERVERLESS_NETWORK_BYTES_OUT AlertViewMetricName = "SERVERLESS_NETWORK_BYTES_OUT"
	// SERVERLESS_NETWORK_NUM_REQUESTS.
	AlertViewMetricName_SERVERLESS_NETWORK_NUM_REQUESTS AlertViewMetricName = "SERVERLESS_NETWORK_NUM_REQUESTS"
	// SERVERLESS_OPCOUNTER_CMD.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_CMD AlertViewMetricName = "SERVERLESS_OPCOUNTER_CMD"
	// SERVERLESS_OPCOUNTER_DELETE.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_DELETE AlertViewMetricName = "SERVERLESS_OPCOUNTER_DELETE"
	// SERVERLESS_OPCOUNTER_GETMORE.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_GETMORE AlertViewMetricName = "SERVERLESS_OPCOUNTER_GETMORE"
	// SERVERLESS_OPCOUNTER_INSERT.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_INSERT AlertViewMetricName = "SERVERLESS_OPCOUNTER_INSERT"
	// SERVERLESS_OPCOUNTER_QUERY.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_QUERY AlertViewMetricName = "SERVERLESS_OPCOUNTER_QUERY"
	// SERVERLESS_OPCOUNTER_UPDATE.
	AlertViewMetricName_SERVERLESS_OPCOUNTER_UPDATE AlertViewMetricName = "SERVERLESS_OPCOUNTER_UPDATE"
	// SERVERLESS_TOTAL_READ_UNITS.
	AlertViewMetricName_SERVERLESS_TOTAL_READ_UNITS AlertViewMetricName = "SERVERLESS_TOTAL_READ_UNITS"
	// SERVERLESS_TOTAL_WRITE_UNITS.
	AlertViewMetricName_SERVERLESS_TOTAL_WRITE_UNITS AlertViewMetricName = "SERVERLESS_TOTAL_WRITE_UNITS"
	// TICKETS_AVAILABLE_READS.
	AlertViewMetricName_TICKETS_AVAILABLE_READS AlertViewMetricName = "TICKETS_AVAILABLE_READS"
	// TICKETS_AVAILABLE_WRITES.
	AlertViewMetricName_TICKETS_AVAILABLE_WRITES AlertViewMetricName = "TICKETS_AVAILABLE_WRITES"
)

