// MongoDB Atlas CDK Construct Library for AWS CloudFormation Resources
package mongodbatlas


// Event type that triggers an alert.
type CfnAlertConfigurationPropsEventTypeName string

const (
	// AWS_ENCRYPTION_KEY_NEEDS_ROTATION.
	CfnAlertConfigurationPropsEventTypeName_AWS_ENCRYPTION_KEY_NEEDS_ROTATION CfnAlertConfigurationPropsEventTypeName = "AWS_ENCRYPTION_KEY_NEEDS_ROTATION"
	// AZURE_ENCRYPTION_KEY_NEEDS_ROTATION.
	CfnAlertConfigurationPropsEventTypeName_AZURE_ENCRYPTION_KEY_NEEDS_ROTATION CfnAlertConfigurationPropsEventTypeName = "AZURE_ENCRYPTION_KEY_NEEDS_ROTATION"
	// CLUSTER_MONGOS_IS_MISSING.
	CfnAlertConfigurationPropsEventTypeName_CLUSTER_MONGOS_IS_MISSING CfnAlertConfigurationPropsEventTypeName = "CLUSTER_MONGOS_IS_MISSING"
	// CPS_RESTORE_FAILED.
	CfnAlertConfigurationPropsEventTypeName_CPS_RESTORE_FAILED CfnAlertConfigurationPropsEventTypeName = "CPS_RESTORE_FAILED"
	// CPS_RESTORE_SUCCESSFUL.
	CfnAlertConfigurationPropsEventTypeName_CPS_RESTORE_SUCCESSFUL CfnAlertConfigurationPropsEventTypeName = "CPS_RESTORE_SUCCESSFUL"
	// CPS_SNAPSHOT_BEHIND.
	CfnAlertConfigurationPropsEventTypeName_CPS_SNAPSHOT_BEHIND CfnAlertConfigurationPropsEventTypeName = "CPS_SNAPSHOT_BEHIND"
	// CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED.
	CfnAlertConfigurationPropsEventTypeName_CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED CfnAlertConfigurationPropsEventTypeName = "CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED"
	// CPS_SNAPSHOT_FALLBACK_FAILED.
	CfnAlertConfigurationPropsEventTypeName_CPS_SNAPSHOT_FALLBACK_FAILED CfnAlertConfigurationPropsEventTypeName = "CPS_SNAPSHOT_FALLBACK_FAILED"
	// CPS_SNAPSHOT_FALLBACK_SUCCESSFUL.
	CfnAlertConfigurationPropsEventTypeName_CPS_SNAPSHOT_FALLBACK_SUCCESSFUL CfnAlertConfigurationPropsEventTypeName = "CPS_SNAPSHOT_FALLBACK_SUCCESSFUL"
	// CPS_SNAPSHOT_SUCCESSFUL.
	CfnAlertConfigurationPropsEventTypeName_CPS_SNAPSHOT_SUCCESSFUL CfnAlertConfigurationPropsEventTypeName = "CPS_SNAPSHOT_SUCCESSFUL"
	// CREDIT_CARD_ABOUT_TO_EXPIRE.
	CfnAlertConfigurationPropsEventTypeName_CREDIT_CARD_ABOUT_TO_EXPIRE CfnAlertConfigurationPropsEventTypeName = "CREDIT_CARD_ABOUT_TO_EXPIRE"
	// DAILY_BILL_OVER_THRESHOLD.
	CfnAlertConfigurationPropsEventTypeName_DAILY_BILL_OVER_THRESHOLD CfnAlertConfigurationPropsEventTypeName = "DAILY_BILL_OVER_THRESHOLD"
	// GCP_ENCRYPTION_KEY_NEEDS_ROTATION.
	CfnAlertConfigurationPropsEventTypeName_GCP_ENCRYPTION_KEY_NEEDS_ROTATION CfnAlertConfigurationPropsEventTypeName = "GCP_ENCRYPTION_KEY_NEEDS_ROTATION"
	// HOST_DOWN.
	CfnAlertConfigurationPropsEventTypeName_HOST_DOWN CfnAlertConfigurationPropsEventTypeName = "HOST_DOWN"
	// JOINED_GROUP.
	CfnAlertConfigurationPropsEventTypeName_JOINED_GROUP CfnAlertConfigurationPropsEventTypeName = "JOINED_GROUP"
	// NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK.
	CfnAlertConfigurationPropsEventTypeName_NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK CfnAlertConfigurationPropsEventTypeName = "NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK"
	// NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK.
	CfnAlertConfigurationPropsEventTypeName_NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK CfnAlertConfigurationPropsEventTypeName = "NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK"
	// NO_PRIMARY.
	CfnAlertConfigurationPropsEventTypeName_NO_PRIMARY CfnAlertConfigurationPropsEventTypeName = "NO_PRIMARY"
	// OUTSIDE_METRIC_THRESHOLD.
	CfnAlertConfigurationPropsEventTypeName_OUTSIDE_METRIC_THRESHOLD CfnAlertConfigurationPropsEventTypeName = "OUTSIDE_METRIC_THRESHOLD"
	// OUTSIDE_SERVERLESS_METRIC_THRESHOLD.
	CfnAlertConfigurationPropsEventTypeName_OUTSIDE_SERVERLESS_METRIC_THRESHOLD CfnAlertConfigurationPropsEventTypeName = "OUTSIDE_SERVERLESS_METRIC_THRESHOLD"
	// OUTSIDE_REALM_METRIC_THRESHOLD.
	CfnAlertConfigurationPropsEventTypeName_OUTSIDE_REALM_METRIC_THRESHOLD CfnAlertConfigurationPropsEventTypeName = "OUTSIDE_REALM_METRIC_THRESHOLD"
	// PENDING_INVOICE_OVER_THRESHOLD.
	CfnAlertConfigurationPropsEventTypeName_PENDING_INVOICE_OVER_THRESHOLD CfnAlertConfigurationPropsEventTypeName = "PENDING_INVOICE_OVER_THRESHOLD"
	// PRIMARY_ELECTED.
	CfnAlertConfigurationPropsEventTypeName_PRIMARY_ELECTED CfnAlertConfigurationPropsEventTypeName = "PRIMARY_ELECTED"
	// REMOVED_FROM_GROUP.
	CfnAlertConfigurationPropsEventTypeName_REMOVED_FROM_GROUP CfnAlertConfigurationPropsEventTypeName = "REMOVED_FROM_GROUP"
	// REPLICATION_OPLOG_WINDOW_RUNNING_OUT.
	CfnAlertConfigurationPropsEventTypeName_REPLICATION_OPLOG_WINDOW_RUNNING_OUT CfnAlertConfigurationPropsEventTypeName = "REPLICATION_OPLOG_WINDOW_RUNNING_OUT"
	// TOO_MANY_ELECTIONS.
	CfnAlertConfigurationPropsEventTypeName_TOO_MANY_ELECTIONS CfnAlertConfigurationPropsEventTypeName = "TOO_MANY_ELECTIONS"
	// USER_ROLES_CHANGED_AUDIT.
	CfnAlertConfigurationPropsEventTypeName_USER_ROLES_CHANGED_AUDIT CfnAlertConfigurationPropsEventTypeName = "USER_ROLES_CHANGED_AUDIT"
	// USERS_WITHOUT_MULTIFACTOR_AUTH.
	CfnAlertConfigurationPropsEventTypeName_USERS_WITHOUT_MULTIFACTOR_AUTH CfnAlertConfigurationPropsEventTypeName = "USERS_WITHOUT_MULTIFACTOR_AUTH"
)

