// MongoDB Atlas CDK Construct Library for AWS CloudFormation Resources
package awscdkresourcesmongodbatlas


// Incident that triggered this alert.
type AlertViewEventTypeName string

const (
	// AWS_ENCRYPTION_KEY_NEEDS_ROTATION.
	AlertViewEventTypeName_AWS_ENCRYPTION_KEY_NEEDS_ROTATION AlertViewEventTypeName = "AWS_ENCRYPTION_KEY_NEEDS_ROTATION"
	// AZURE_ENCRYPTION_KEY_NEEDS_ROTATION.
	AlertViewEventTypeName_AZURE_ENCRYPTION_KEY_NEEDS_ROTATION AlertViewEventTypeName = "AZURE_ENCRYPTION_KEY_NEEDS_ROTATION"
	// CLUSTER_MONGOS_IS_MISSING.
	AlertViewEventTypeName_CLUSTER_MONGOS_IS_MISSING AlertViewEventTypeName = "CLUSTER_MONGOS_IS_MISSING"
	// CPS_RESTORE_FAILED.
	AlertViewEventTypeName_CPS_RESTORE_FAILED AlertViewEventTypeName = "CPS_RESTORE_FAILED"
	// CPS_RESTORE_SUCCESSFUL.
	AlertViewEventTypeName_CPS_RESTORE_SUCCESSFUL AlertViewEventTypeName = "CPS_RESTORE_SUCCESSFUL"
	// CPS_SNAPSHOT_BEHIND.
	AlertViewEventTypeName_CPS_SNAPSHOT_BEHIND AlertViewEventTypeName = "CPS_SNAPSHOT_BEHIND"
	// CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED.
	AlertViewEventTypeName_CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED AlertViewEventTypeName = "CPS_SNAPSHOT_DOWNLOAD_REQUEST_FAILED"
	// CPS_SNAPSHOT_FALLBACK_FAILED.
	AlertViewEventTypeName_CPS_SNAPSHOT_FALLBACK_FAILED AlertViewEventTypeName = "CPS_SNAPSHOT_FALLBACK_FAILED"
	// CPS_SNAPSHOT_FALLBACK_SUCCESSFUL.
	AlertViewEventTypeName_CPS_SNAPSHOT_FALLBACK_SUCCESSFUL AlertViewEventTypeName = "CPS_SNAPSHOT_FALLBACK_SUCCESSFUL"
	// CPS_SNAPSHOT_SUCCESSFUL.
	AlertViewEventTypeName_CPS_SNAPSHOT_SUCCESSFUL AlertViewEventTypeName = "CPS_SNAPSHOT_SUCCESSFUL"
	// CREDIT_CARD_ABOUT_TO_EXPIRE.
	AlertViewEventTypeName_CREDIT_CARD_ABOUT_TO_EXPIRE AlertViewEventTypeName = "CREDIT_CARD_ABOUT_TO_EXPIRE"
	// DAILY_BILL_OVER_THRESHOLD.
	AlertViewEventTypeName_DAILY_BILL_OVER_THRESHOLD AlertViewEventTypeName = "DAILY_BILL_OVER_THRESHOLD"
	// GCP_ENCRYPTION_KEY_NEEDS_ROTATION.
	AlertViewEventTypeName_GCP_ENCRYPTION_KEY_NEEDS_ROTATION AlertViewEventTypeName = "GCP_ENCRYPTION_KEY_NEEDS_ROTATION"
	// HOST_DOWN.
	AlertViewEventTypeName_HOST_DOWN AlertViewEventTypeName = "HOST_DOWN"
	// JOINED_GROUP.
	AlertViewEventTypeName_JOINED_GROUP AlertViewEventTypeName = "JOINED_GROUP"
	// NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK.
	AlertViewEventTypeName_NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK AlertViewEventTypeName = "NDS_X509_USER_AUTHENTICATION_CUSTOMER_CA_EXPIRATION_CHECK"
	// NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK.
	AlertViewEventTypeName_NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK AlertViewEventTypeName = "NDS_X509_USER_AUTHENTICATION_MANAGED_USER_CERTS_EXPIRATION_CHECK"
	// NO_PRIMARY.
	AlertViewEventTypeName_NO_PRIMARY AlertViewEventTypeName = "NO_PRIMARY"
	// OUTSIDE_METRIC_THRESHOLD.
	AlertViewEventTypeName_OUTSIDE_METRIC_THRESHOLD AlertViewEventTypeName = "OUTSIDE_METRIC_THRESHOLD"
	// OUTSIDE_SERVERLESS_METRIC_THRESHOLD.
	AlertViewEventTypeName_OUTSIDE_SERVERLESS_METRIC_THRESHOLD AlertViewEventTypeName = "OUTSIDE_SERVERLESS_METRIC_THRESHOLD"
	// PENDING_INVOICE_OVER_THRESHOLD.
	AlertViewEventTypeName_PENDING_INVOICE_OVER_THRESHOLD AlertViewEventTypeName = "PENDING_INVOICE_OVER_THRESHOLD"
	// PRIMARY_ELECTED.
	AlertViewEventTypeName_PRIMARY_ELECTED AlertViewEventTypeName = "PRIMARY_ELECTED"
	// REMOVED_FROM_GROUP.
	AlertViewEventTypeName_REMOVED_FROM_GROUP AlertViewEventTypeName = "REMOVED_FROM_GROUP"
	// REPLICATION_OPLOG_WINDOW_RUNNING_OUT.
	AlertViewEventTypeName_REPLICATION_OPLOG_WINDOW_RUNNING_OUT AlertViewEventTypeName = "REPLICATION_OPLOG_WINDOW_RUNNING_OUT"
	// TOO_MANY_ELECTIONS.
	AlertViewEventTypeName_TOO_MANY_ELECTIONS AlertViewEventTypeName = "TOO_MANY_ELECTIONS"
	// USERS_WITHOUT_MULTIFACTOR_AUTH.
	AlertViewEventTypeName_USERS_WITHOUT_MULTIFACTOR_AUTH AlertViewEventTypeName = "USERS_WITHOUT_MULTIFACTOR_AUTH"
)

